# Generated by Django 2.1.2 on 2018-11-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaproducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidoespecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relleno', models.CharField(max_length=20)),
                ('galleta', models.CharField(max_length=20)),
                ('cobertura', models.CharField(max_length=20)),
                ('figura', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
